services:
  #proxy - Traefik
  proxy:
    container_name: Traefik
    image: traefik:v3.1.6
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "${TRAEFIK_PORT}:80"
      # The Web UI (enabled by --api.insecure=true)
      - "${TRAEFIK_ADMIN_PORT}:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    #env_file: ".env"
  #redis
  #mariadb
  #processmaker
